// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Eu3DD_T8UAXr_RfpbBJfP7m326F9npk',
    appId: '1:1036852672581:web:cca98f0a70b6bd127e4b2c',
    messagingSenderId: '1036852672581',
    projectId: 'pollas-play',
    authDomain: 'pollas-play.firebaseapp.com',
    storageBucket: 'pollas-play.appspot.com',
    measurementId: 'G-Q62VBT4XVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUcvb8wZW-UujcpM5jqR6ZF3fI8KRqhnM',
    appId: '1:1036852672581:android:af7b35f64bb15a817e4b2c',
    messagingSenderId: '1036852672581',
    projectId: 'pollas-play',
    storageBucket: 'pollas-play.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRB9z4d5_PCxY_BHmbZH6lgrGo5vCqWo8',
    appId: '1:1036852672581:ios:ca88224dfd56ffd67e4b2c',
    messagingSenderId: '1036852672581',
    projectId: 'pollas-play',
    storageBucket: 'pollas-play.appspot.com',
    iosClientId: '1036852672581-83knfao5aieij9fmlsm4itv34cneja34.apps.googleusercontent.com',
    iosBundleId: 'com.example.eFecta',
  );
}
